# Generated by Django 6.0.6 on 2026-09-17 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_remove_review_property_alter_chatmessage_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='ID Сессии гостя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Чат с гостем',
                'verbose_name_plural': 'Чаты с гостями',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('client', 'Клиент'), ('staff', 'Сотрудник')], max_length=10, verbose_name='Отправитель')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.guestchat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Сообщение гостя',
                'verbose_name_plural': 'Сообщения гостей',
                'ordering': ['sent_at'],
            },
        ),
    ]
