# Generated by Django 6.0.6 on 2026-06-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingrequest',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Назначенное время'),
        ),
    ]
