# Generated by Django 6.0.6 on 2026-06-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_viewingrequest_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='yookassa_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа ЮKassa'),
        ),
    ]
