# Generated by Django 6.0.6 on 2026-09-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_payment_yookassa_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewingrequest',
            options={'verbose_name': 'Заявка на просмотр', 'verbose_name_plural': 'Заявки на просмотры'},
        ),
        migrations.AlterField(
            model_name='viewingrequest',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланированное время'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
