# Generated by Django 6.0.6 on 2026-09-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_viewingrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('time_to_call', models.CharField(blank=True, max_length=100, null=True, verbose_name='Время звонка')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заказ звонка',
                'verbose_name_plural': 'Заказы звонков',
            },
        ),
    ]
